# Generated by Django 3.1.4 on 2022-12-31 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20221231_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_organizer',
            new_name='is_organizor',
        ),
    ]
